# import os
#
# os.startfile(r'D:\pyqtStudy\Qevent.xmind')
# os.startfile(r'D:\pyqtStudy\Draw.xmind')
# os.startfile(r'D:\pyqtStudy\QtCore&QtGui.xmind')
# os.startfile(r'D:\pyqtStudy\QtWidgets.xmind')
# os.startfile(r'D:\ProgramFiles\Qt\Tools\QtCreator\bin\qtcreator.exe')
# os.startfile(r'D:\ProgramFiles\PyCharm\bin\pycharm64.exe')
# os.startfile(r'D:\ProgramFiles\Microsoft VS Code\Code.exe')
# os.startfile(r'D:\pyqtStudy\Python Qt GUI与数据可视化编程.md')

from pathlib import *
pp = PurePath('setup.py')
print(type(pp))
pp = PurePath('crazyit', 'some/path', 'info')
print(pp)
pp = PurePath(Path('crazyit'), Path('info'))
print(pp)
pp = PurePosixPath('crazyit', 'some/path', 'info')
print(pp)
pp = PurePath()
print(pp)
pp = PurePosixPath('/etc', '/usr', 'lib64')
print(pp)
pp = PureWindowsPath('c:/Windows', 'd:info')
print(pp)
pp = PureWindowsPath('c:/Windows', '/Program Files')
print(pp)
pp = PurePath('foo//bar')
print(pp)
pp = PurePath('foo/./bar')
print(pp)
pp = PurePath('foo/../bar')
print(pp)

print(PurePosixPath('info') == PurePosixPath('INFO'))
print(PureWindowsPath('info') == PureWindowsPath('INFO'))
print(PurePosixPath('D:') < PurePosixPath('c:'))
print(PureWindowsPath('D:') > PureWindowsPath('c'))
print(PureWindowsPath('crazyit') == PurePosixPath('crazyit'))
# print(PureWindowsPath('info') < PurePosixPath('info'))

pp = PureWindowsPath('abc')
print(pp / 'xyz' / 'wawa')
pp = PurePosixPath('abc')
print(pp / 'xyz' / 'wawa')
pp2 = PurePosixPath('haha', 'hehe')
print(pp / pp2)

pp = PureWindowsPath('abc', 'xyz', 'wawa')
print(str(pp))
pp = PurePosixPath('abc', 'xyz', 'swawa')
print(str(pp))